version: '3.8'
networks:
  inner:
    external: true
services:
  web:
    image: nginx
    container_name: box
    environment:
      - LANG=zh_CN.UTF-8
      - LANGUAGE=zh_CN.UTF-8
      - LC_ALL=zh_CN.UTF-8
    volumes:
      - /homeshare/webs/box/html:/usr/share/nginx/html:ro
    ports:
      - "85:80"
    restart: always
    networks:
      inner:
        ipv4_address: 172.2.0.8
